# Generated by Django 5.2.7 on 2025-11-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='reason',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='student',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appeal',
            name='student_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
