# Generated by Django 5.2.7 on 2025-11-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_reason_appeal_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='message',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='subject',
        ),
        migrations.AddField(
            model_name='appeal',
            name='assignment',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='student',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
